-- Your SQL goes here

-- temperatures are saved in the unit 0.1 deg

CREATE TABLE temperatures (
  id INTEGER PRIMARY KEY NOT NULL,
  r0 INTEGER NOT NULL,
  r1 INTEGER NOT NULL,
  r2 INTEGER NOT NULL,
  r3 INTEGER NOT NULL,
  r4 INTEGER NOT NULL,
  r5 INTEGER NOT NULL,
  t0 INTEGER NOT NULL,
  t1 INTEGER NOT NULL,
  t2 INTEGER NOT NULL,
  t3 INTEGER NOT NULL,
  t4 INTEGER NOT NULL,
  t5 INTEGER NOT NULL,
  timestamp DATETIME NOT NULL
)
